"""Pre-commit hook: enforce strategic content-quality sections.

Checks:
1. Key README/docs pages include required strategic headings.
2. docs/index.md uses shared README snippets for MCP/philosophy parity.
3. Generated technical-reference pages retain auto-generated markers.
"""

from __future__ import annotations

import sys
from pathlib import Path

REQUIRED_HEADINGS: dict[Path, tuple[str, ...]] = {
    Path("README.md"): (
        "## Why MCP for Zen Analysis",
        "## Zen Philosophy",
    ),
    Path("docs/index.md"): (
        "## Why MCP",
        "## Zen Philosophy",
        "## Choose Your Path",
    ),
    Path("docs/contributing/content-quality.md"): (
        "## Source-of-truth map",
        "## Editorial standards",
        "## Release checklist",
    ),
}

REQUIRED_SNIPPETS: dict[Path, tuple[str, ...]] = {
    Path("docs/index.md"): (
        '--8<-- "README.md:why-mcp"',
        '--8<-- "README.md:zen-philosophy"',
    ),
}

GENERATED_REFERENCE_MARKERS: dict[Path, tuple[str, ...]] = {
    Path("docs/user-guide/cli-reference.md"): ("Auto-generated", "cli.py"),
    Path("docs/user-guide/mcp-tools-reference.md"): ("Auto-generated", "server.py"),
    Path("docs/config.md"): ("Generated by", "scripts/generate_config_docs.py"),
}


def _read(path: Path, errors: list[str]) -> str:
    if not path.exists():
        errors.append(f"{path}: file not found")
        return ""
    return path.read_text(encoding="utf-8")


def _check_required_headings(errors: list[str]) -> None:
    for path, headings in REQUIRED_HEADINGS.items():
        text = _read(path, errors)
        if not text:
            continue
        errors.extend(
            f"{path}: missing required heading '{heading}'"
            for heading in headings
            if heading not in text
        )


def _check_required_snippets(errors: list[str]) -> None:
    for path, snippets in REQUIRED_SNIPPETS.items():
        text = _read(path, errors)
        if not text:
            continue
        errors.extend(
            f"{path}: missing required snippet include '{snippet}'"
            for snippet in snippets
            if snippet not in text
        )


def _check_generated_markers(errors: list[str]) -> None:
    for path, markers in GENERATED_REFERENCE_MARKERS.items():
        text = _read(path, errors)
        if not text:
            continue
        errors.extend(
            f"{path}: missing generated-doc marker '{marker}'"
            for marker in markers
            if marker not in text
        )


def main() -> int:
    errors: list[str] = []

    _check_required_headings(errors)
    _check_required_snippets(errors)
    _check_generated_markers(errors)

    if errors:
        print("❌ Content quality checks failed:")
        for error in errors:
            print(f"  • {error}")
        return 1

    print("✅ Content quality checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
