"""Generate a concrete perspective-aware CLI example for docs inclusion.

Run::

    uv run python scripts/generate_cli_output_example.py          # write file
    uv run python scripts/generate_cli_output_example.py --check   # CI dry-run

The script invokes the live CLI against a deterministic fixture file and writes
the captured terminal output to ``docs/includes/generated/cli-output-example.md``.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = ROOT / "docs" / "includes" / "generated" / "cli-output-example.md"
FIXTURE_FILE = (
    ROOT / "tests" / "fixtures" / "cli_docs" / "tests" / "test_perspective_example.py"
)
TERMINAL_WIDTH = "88"
COMMAND = [
    "zen",
    "check",
    "tests/fixtures/cli_docs/tests/test_perspective_example.py",
    "--perspective",
    "testing",
    "--show-files",
]


def _run_cli_example() -> str:
    """Capture terminal output from the live CLI for the docs fixture."""
    env = os.environ.copy()
    src_dir = ROOT / "src"
    existing_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = (
        str(src_dir)
        if not existing_pythonpath
        else f"{src_dir}{os.pathsep}{existing_pythonpath}"
    )
    env["COLUMNS"] = TERMINAL_WIDTH

    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "mcp_zen_of_languages.cli",
            *COMMAND[1:],
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    if result.returncode != 0:
        msg = (
            "Failed to generate the CLI example.\n"
            f"Command: {' '.join(COMMAND)}\n\n"
            f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
        )
        raise RuntimeError(msg)
    return "\n".join(line.rstrip() for line in result.stdout.rstrip().splitlines())


def generate() -> str:
    """Build the markdown include from the live CLI output."""
    fixture_path = FIXTURE_FILE.relative_to(ROOT).as_posix()
    output = _run_cli_example()
    return "\n".join(
        (
            "<!-- Auto-generated by scripts/generate_cli_output_example.py. Do not edit manually. -->",
            "",
            "### Perspective-aware CLI example",
            "",
            "This example is captured from the live CLI against a deterministic pytest-style fixture so docs stay aligned with the testing perspective surface.",
            "",
            "```bash",
            " ".join(COMMAND),
            "```",
            "",
            "```text",
            output,
            "```",
            "",
            f"Fixture: `{fixture_path}`",
            "",
        ),
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a perspective-aware CLI output example for docs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Dry-run: exit 1 if the generated artifact would change.",
    )
    args = parser.parse_args()

    content = generate()

    if args.check:
        if OUTPUT_FILE.exists() and OUTPUT_FILE.read_text(encoding="utf-8") == content:
            print(f"✅ {OUTPUT_FILE.relative_to(ROOT)} is up to date.")
            sys.exit(0)
        print(f"❌ {OUTPUT_FILE.relative_to(ROOT)} is out of date. Run:")
        print("   uv run python scripts/generate_cli_output_example.py")
        sys.exit(1)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"✅ Wrote {OUTPUT_FILE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
