from __future__ import annotations

from pathlib import Path

from mcp_zen_of_languages.analyzers.base import AnalyzerConfig
from mcp_zen_of_languages.languages.configs import DetectorConfig


_RUNTIME_ONLY_CONFIG_FIELDS = frozenset(
    {
        "type",
        "principle_id",
        "principle",
        "severity",
        "violation_messages",
        "detectable_patterns",
        "recommended_alternative",
        "rule_contexts",
    },
)


HEADER = """---
title: Configuration Reference
description: Generated reference for zen-config analyzer defaults and constraints.
icon: material/cog
tags:
  - CLI
  - Configuration
---

# Configuration Reference

This project loads configuration from `zen-config.yaml` in the current working
directory or the first parent directory that contains `pyproject.toml`.

> Generated by `python scripts/generate_config_docs.py`. Do not edit manually.

## Analyzer Defaults (auto-generated)
"""


def _format_field(name: str, field) -> str:
    annotation = repr(field.annotation).replace("<class '", "").replace("'>", "")
    if field.default_factory is not None:
        default = field.default_factory()
    else:
        default = field.default if field.default is not None else "None"
    if isinstance(default, type):
        default = default.__name__
    description = field.description or ""
    suffix = f" — {description}" if description else ""
    return f"- `{name}`: `{annotation}` (default: `{default}`){suffix}\n"


def main() -> None:
    output = [HEADER]
    output.extend(
        _format_field(name, field)
        for name, field in AnalyzerConfig.model_fields.items()
        if name not in set(DetectorConfig.model_fields) | _RUNTIME_ONLY_CONFIG_FIELDS
    )
    output.extend(
        (
            "\n## Notes\n",
            "- Detector metrics must match detector config field names exactly "
            "(strict projection).\n",
            "- Unknown `metrics` keys in rules will raise a validation error during "
            "pipeline construction.\n",
            "- Language module folders are expected to include `__init__.py`, "
            "`analyzer.py`, `detectors.py`, `mapping.py`, and `rules.py`.\n",
        ),
    )
    docs_path = Path(__file__).resolve().parents[1] / "docs" / "config.md"
    docs_path.write_text("".join(output), encoding="utf-8")


if __name__ == "__main__":
    main()
